name: 'Generate Release Reports'
description: 'Generates comprehensive quality reports for Rust project releases'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  version:
    description: 'Release version number (e.g., 1.0.0)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12
      with:
        extra-conf: |
          experimental-features = nix-command flakes

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Check for justfile
      id: check-just
      shell: bash
      run: |
        if [ -f "justfile" ] && grep -q "release-reports" justfile; then
          echo "has-just=true" >> $GITHUB_OUTPUT
        else
          echo "has-just=false" >> $GITHUB_OUTPUT
        fi

    - name: Generate reports via justfile
      if: steps.check-just.outputs.has-just == 'true'
      shell: bash
      run: |
        nix develop --command just release-reports ${{ inputs.version }}

    - name: Generate reports manually
      if: steps.check-just.outputs.has-just == 'false'
      shell: bash
      run: |
        mkdir -p release-artifacts/reports
        mkdir -p release-artifacts/ai-docs

        # Clippy report
        echo "# Clippy Report - Zero Warnings Tolerance" > release-artifacts/reports/clippy-report.md
        echo "" >> release-artifacts/reports/clippy-report.md
        echo "**Version:** ${{ inputs.version }}" >> release-artifacts/reports/clippy-report.md
        echo "**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> release-artifacts/reports/clippy-report.md
        echo "" >> release-artifacts/reports/clippy-report.md
        echo "\`\`\`" >> release-artifacts/reports/clippy-report.md
        nix develop --command cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery 2>&1 | tee -a release-artifacts/reports/clippy-report.md || true
        echo "\`\`\`" >> release-artifacts/reports/clippy-report.md

        # Security audit
        echo "# Security Audit Report" > release-artifacts/reports/security-audit.md
        echo "" >> release-artifacts/reports/security-audit.md
        echo "**Version:** ${{ inputs.version }}" >> release-artifacts/reports/security-audit.md
        echo "" >> release-artifacts/reports/security-audit.md
        nix develop --command cargo audit 2>&1 >> release-artifacts/reports/security-audit.md || echo "No vulnerabilities found" >> release-artifacts/reports/security-audit.md

        # SBOM
        echo "# Software Bill of Materials" > release-artifacts/reports/sbom.md
        echo "" >> release-artifacts/reports/sbom.md
        echo "**Version:** ${{ inputs.version }}" >> release-artifacts/reports/sbom.md
        echo "" >> release-artifacts/reports/sbom.md
        echo "\`\`\`" >> release-artifacts/reports/sbom.md
        nix develop --command cargo tree --all-features >> release-artifacts/reports/sbom.md
        echo "\`\`\`" >> release-artifacts/reports/sbom.md

        # Coverage (if tarpaulin available)
        echo "# Test Coverage Report" > release-artifacts/reports/coverage-report.md
        echo "" >> release-artifacts/reports/coverage-report.md
        echo "**Version:** ${{ inputs.version }}" >> release-artifacts/reports/coverage-report.md
        echo "" >> release-artifacts/reports/coverage-report.md
        nix develop --command cargo tarpaulin --all-features --out Stdout 2>&1 >> release-artifacts/reports/coverage-report.md || echo "Coverage tool not available" >> release-artifacts/reports/coverage-report.md

        # Copy AGENTS.md if exists
        if [ -f "AGENTS.md.release" ]; then
          cp AGENTS.md.release release-artifacts/ai-docs/AGENTS.md
        fi

        # Copy CHANGELOG.md if exists
        if [ -f "CHANGELOG.md" ]; then
          cp CHANGELOG.md release-artifacts/
        fi

    - name: Create archives
      shell: bash
      run: |
        cd release-artifacts
        tar czf ../release-reports-v${{ inputs.version }}.tar.gz .
        cd ..
        zip -r release-reports-v${{ inputs.version }}.zip release-artifacts/

    - name: Summary
      shell: bash
      run: |
        echo "### Release Reports Generated 📊" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Version: **${{ inputs.version }}**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Reports created:" >> $GITHUB_STEP_SUMMARY
        echo "- Clippy report (zero warnings validation)" >> $GITHUB_STEP_SUMMARY
        echo "- Security audit" >> $GITHUB_STEP_SUMMARY
        echo "- SBOM (dependency tree)" >> $GITHUB_STEP_SUMMARY
        echo "- Coverage report" >> $GITHUB_STEP_SUMMARY
        if [ -f "release-artifacts/ai-docs/AGENTS.md" ]; then
          echo "- AI/LLM documentation" >> $GITHUB_STEP_SUMMARY
        fi
        if [ -f "release-artifacts/CHANGELOG.md" ]; then
          echo "- Changelog" >> $GITHUB_STEP_SUMMARY
        fi
