name: 'Setup Nix + Rust Environment'
description: 'Sets up Nix with comprehensive caching for Rust projects'
branding:
  icon: 'package'
  color: 'orange'

inputs:
  cachix-name:
    description: 'Cachix cache name (optional)'
    required: false
    default: ''
  cachix-auth-token:
    description: 'Cachix auth token (optional, use secrets)'
    required: false
    default: ''
  enable-flakehub:
    description: 'Enable FlakeHub cache (Linux only)'
    required: false
    default: 'true'
  enable-github-cache:
    description: 'Enable GitHub Actions cache'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Cache Nix Store
      if: inputs.enable-github-cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/nix
          /nix/var/nix
        key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
        restore-keys: |
          nix-${{ runner.os }}-

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v12
      with:
        extra-conf: |
          experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Setup FlakeHub Cache
      if: inputs.enable-flakehub == 'true' && runner.os == 'Linux'
      uses: DeterminateSystems/flakehub-cache-action@v7

    - name: Setup Cachix Cache
      if: inputs.cachix-name != ''
      uses: cachix/cachix-action@v15
      with:
        name: ${{ inputs.cachix-name }}
        authToken: ${{ inputs.cachix-auth-token }}

    - name: Show Nix info
      shell: bash
      run: |
        echo "Nix version:"
        nix --version
        echo ""
        echo "Flake info:"
        nix flake show || true
