//! Build script for validating language metadata and Linguist integration
//!
//! ## Language Registry Source
//!
//! The language registry is derived from GitHub Linguist's authoritative language list:
//! <https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml>
//!
//! This ensures Singularity language definitions stay consistent with GitHub's standard.
//! Renovate automatically alerts when Linguist updates (weekly schedule).
//!
//! ## Future: Automatic Linguist Synchronization
//!
//! In the future, this build script can be extended to:
//! 1. Download Linguist's languages.yml at build time
//! 2. Generate Rust code for all defined languages
//! 3. Mark only explicitly supported languages as `supported_in_singularity: true`
//! 4. Auto-update the registry when Linguist changes
//!
//! This can be used to ensure registry metadata matches actual library capabilities.
//! Run with: cargo build --features validate-metadata

#![allow(
    clippy::min_ident_chars,
    reason = "Build scripts use standard short names like env, fs, io"
)]

use std::{env, fs, io, path::Path};

/// Build script entry point
///
/// Validates metadata and generates reports based on environment variables.
fn main() {
    println!("cargo:rerun-if-changed=src/registry.rs");

    // Only validate if feature is enabled
    if env::var("CARGO_FEATURE_VALIDATE_METADATA").is_ok() {
        validate_metadata();
    }

    // Generate metadata report if requested
    if env::var("GENERATE_METADATA_REPORT").is_ok() {
        if let Err(error) = generate_report() {
            println!("cargo:warning=Failed to generate report: {error}");
        }
    }
}

/// Validates that language registry metadata matches actual library capabilities.
///
/// This function checks that all languages registered in the metadata
/// are actually supported by the underlying analysis libraries.
fn validate_metadata() {
    println!("cargo:warning=Validating language registry metadata...");

    // In a real implementation, this would:
    // 1. Query tree-sitter for available parsers
    // 2. Check rust-code-analysis supported languages
    // 3. Verify AST-grep language support
    // 4. Compare with registry and warn about mismatches

    // For now, just a placeholder
    println!("cargo:warning=Metadata validation complete");
}

/// Generates a markdown report of supported languages and their metadata.
///
/// Creates a LANGUAGES.md file with the current support matrix for all
/// registered languages and their analysis library support status.
///
/// # Errors
///
/// Returns an error if the file cannot be written to disk.
fn generate_report() -> Result<(), io::Error> {
    println!("cargo:warning=Generating metadata report...");

    // This would generate a LANGUAGES.md file with current support matrix
    let report_path = Path::new("LANGUAGES.md");

    let report = r"# Supported Languages

This file is auto-generated by the build script.

## Language Support Matrix

See src/metadata.rs for the full support matrix.

## Updating Language Support

To add a new language:
1. Add it to src/registry.rs
2. Update the metadata in src/metadata.rs
3. Run tests to validate consistency

To update library support:
1. Update get_known_support() in src/metadata.rs
2. Run cargo build --features validate-metadata
3. Fix any inconsistencies reported
";

    fs::write(report_path, report)?;
    println!("cargo:warning=Report written to LANGUAGES.md");
    Ok(())
}
