//! Build script for validating language metadata
//!
//! This can be used to ensure registry metadata matches actual library capabilities.
//! Run with: cargo build --features validate-metadata

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/registry.rs");

    // Only validate if feature is enabled
    if env::var("CARGO_FEATURE_VALIDATE_METADATA").is_ok() {
        validate_metadata();
    }

    // Generate metadata report if requested
    if env::var("GENERATE_METADATA_REPORT").is_ok() {
        generate_report();
    }
}

fn validate_metadata() {
    println!("cargo:warning=Validating language registry metadata...");

    // In a real implementation, this would:
    // 1. Query tree-sitter for available parsers
    // 2. Check rust-code-analysis supported languages
    // 3. Verify AST-grep language support
    // 4. Compare with registry and warn about mismatches

    // For now, just a placeholder
    println!("cargo:warning=Metadata validation complete");
}

fn generate_report() {
    println!("cargo:warning=Generating metadata report...");

    // This would generate a LANGUAGES.md file with current support matrix
    let report_path = Path::new("LANGUAGES.md");

    let report = r"# Supported Languages

This file is auto-generated by the build script.

## Language Support Matrix

See src/metadata.rs for the full support matrix.

## Updating Language Support

To add a new language:
1. Add it to src/registry.rs
2. Update the metadata in src/metadata.rs
3. Run tests to validate consistency

To update library support:
1. Update get_known_support() in src/metadata.rs
2. Run cargo build --features validate-metadata
3. Fix any inconsistencies reported
";

    fs::write(report_path, report).expect("Failed to write report");
    println!("cargo:warning=Report written to LANGUAGES.md");
}
