name: 'Build Crate Package'
description: 'Builds a Rust .crate package with installation instructions'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  version:
    description: 'Crate version number (e.g., 1.0.0)'
    required: true
  allow-dirty:
    description: 'Allow building with uncommitted changes'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install stable Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Get crate name
      id: crate-name
      shell: bash
      run: |
        CRATE_NAME=$(grep '^name = ' Cargo.toml | head -1 | sed 's/.*= "\(.*\)"/\1/')
        echo "name=$CRATE_NAME" >> $GITHUB_OUTPUT
        echo "Crate name: $CRATE_NAME"

    - name: Build crate package
      shell: bash
      run: |
        mkdir -p crate-package
        if [ "${{ inputs.allow-dirty }}" = "true" ]; then
          cargo package --all-features --allow-dirty
        else
          cargo package --all-features
        fi
        cp target/package/${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate crate-package/

    - name: List package contents
      shell: bash
      run: |
        echo "# Crate Package Contents" > crate-package/PACKAGE_CONTENTS.txt
        echo "" >> crate-package/PACKAGE_CONTENTS.txt
        echo "**Package:** ${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate" >> crate-package/PACKAGE_CONTENTS.txt
        echo "**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> crate-package/PACKAGE_CONTENTS.txt
        echo "" >> crate-package/PACKAGE_CONTENTS.txt
        echo "## Files Included" >> crate-package/PACKAGE_CONTENTS.txt
        echo "" >> crate-package/PACKAGE_CONTENTS.txt
        echo "\`\`\`" >> crate-package/PACKAGE_CONTENTS.txt
        tar -tzf target/package/${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate >> crate-package/PACKAGE_CONTENTS.txt
        echo "\`\`\`" >> crate-package/PACKAGE_CONTENTS.txt
        echo "" >> crate-package/PACKAGE_CONTENTS.txt
        echo "## Package Size" >> crate-package/PACKAGE_CONTENTS.txt
        echo "" >> crate-package/PACKAGE_CONTENTS.txt
        ls -lh target/package/${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate | awk '{print "Size: " $5}' >> crate-package/PACKAGE_CONTENTS.txt

    - name: Create installation instructions
      shell: bash
      run: |
        cat > crate-package/INSTALL.md << 'INSTALL_EOF'
        # Installing ${{ steps.crate-name.outputs.name }}

        Version: **${{ inputs.version }}**

        ## Option 1: Add to Cargo.toml (Recommended)

        ```toml
        [dependencies]
        ${{ steps.crate-name.outputs.name }} = { git = "${{ github.server_url }}/${{ github.repository }}", tag = "v${{ inputs.version }}" }
        ```

        ## Option 2: Install from .crate file

        Download the `.crate` file from this release, then:

        ```bash
        cargo install --path ${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate
        ```

        ## Option 3: Use as local dependency

        1. Download and extract the .crate file:

        ```bash
        tar -xzf ${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate
        ```

        2. Add to your Cargo.toml:

        ```toml
        [dependencies]
        ${{ steps.crate-name.outputs.name }} = { path = "./${{ steps.crate-name.outputs.name }}-${{ inputs.version }}" }
        ```

        ## Verification

        After installation, verify the package contents:

        ```bash
        tar -tzf ${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate
        ```

        See `PACKAGE_CONTENTS.txt` for the complete file list.

        ## License

        See LICENSE file in the package or repository.
        INSTALL_EOF

    - name: Summary
      shell: bash
      run: |
        echo "### Crate Package Built 📦" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Crate:** ${{ steps.crate-name.outputs.name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Files created:" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate\`" >> $GITHUB_STEP_SUMMARY
        echo "- \`INSTALL.md\`" >> $GITHUB_STEP_SUMMARY
        echo "- \`PACKAGE_CONTENTS.txt\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Package size:" >> $GITHUB_STEP_SUMMARY
        ls -lh target/package/${{ steps.crate-name.outputs.name }}-${{ inputs.version }}.crate | awk '{print "**" $5 "**"}' >> $GITHUB_STEP_SUMMARY
