// @generated
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from GitHub Linguist patterns (vendor.yml & generated.rb)
// Run: cargo run --bin sync-linguist --features sync-tool
#![rustfmt::skip]

//! Auto-generated file classification patterns from GitHub Linguist.
//! Sources:
//!   • vendor.yml   → vendored path patterns
//!   • generated.rb → generated & binary file patterns

/// Vendored code path patterns (from GitHub Linguist vendor.yml)
pub const VENDORED_PATTERNS_FROM_LINGUIST: &[&str] = &[
    "(.*?)\\.d\\.ts$",
    "(3rd|[Tt]hird)[-_]?[Pp]arty/",
    "([^\\s]*)import\\.(css|less|scss|styl)$",
    "(\\.|-)min\\.(js|css)$",
    "(^|/)BuddyBuildSDK\\.framework/",
    "(^|/)Carthage/",
    "(^|/)Chart\\.js$",
    "(^|/)Control\\.FullScreen\\.css",
    "(^|/)Control\\.FullScreen\\.js",
    "(^|/)Crashlytics\\.framework/",
    "(^|/)Fabric\\.framework/",
    "(^|/)Godeps/_workspace/",
    "(^|/)Jenkinsfile$",
    "(^|/)Leaflet\\.Coordinates-\\d+\\.\\d+\\.\\d+\\.src\\.js$",
    "(^|/)MathJax/",
    "(^|/)MochiKit\\.js$",
    "(^|/)RealmSwift\\.framework",
    "(^|/)Realm\\.framework",
    "(^|/)Sparkle/",
    "(^|/)Vagrantfile$",
    "(^|/)[Bb]ourbon/.*\\.(css|less|scss|styl)$",
    "(^|/)[Cc]ode[Mm]irror/(\\d+\\.\\d+/)?(lib|mode|theme|addon|keymap|demo)",
    "(^|/)[Ee]xtern(als?)?/",
    "(^|/)[Mm]icrosoft([Mm]vc)?([Aa]jax|[Vv]alidation)(\\.debug)?\\.js$",
    "(^|/)[Pp]ackages\\/.+\\.\\d+\\/",
    "(^|/)[Ss]pecs?/fixtures/",
    "(^|/)[Tt]ests?/fixtures/",
    "(^|/)[Vv]+endor/",
    "(^|/)\\.[Dd][Ss]_[Ss]tore$",
    "(^|/)\\.gitattributes$",
    "(^|/)\\.github/",
    "(^|/)\\.gitignore$",
    "(^|/)\\.gitmodules$",
    "(^|/)\\.gitpod\\.Dockerfile$",
    "(^|/)\\.google_apis/",
    "(^|/)\\.indent\\.pro",
    "(^|/)\\.mvn/wrapper/",
    "(^|/)\\.obsidian/",
    "(^|/)\\.osx$",
    "(^|/)\\.sublime-project",
    "(^|/)\\.sublime-workspace",
    "(^|/)\\.teamcity/",
    "(^|/)\\.vscode/",
    "(^|/)\\.yarn/plugins/",
    "(^|/)\\.yarn/releases/",
    "(^|/)\\.yarn/sdks/",
    "(^|/)\\.yarn/unplugged/",
    "(^|/)\\.yarn/versions/",
    "(^|/)_esy$",
    "(^|/)ace-builds/",
    "(^|/)aclocal\\.m4",
    "(^|/)activator$",
    "(^|/)activator\\.bat$",
    "(^|/)admin_media/",
    "(^|/)angular([^.]*)\\.js$",
    "(^|/)animate\\.(css|less|scss|styl)$",
    "(^|/)bootbox\\.js",
    "(^|/)bootstrap([^/.]*)(\\..*)?\\.(js|css|less|scss|styl)$",
    "(^|/)bootstrap-datepicker/",
    "(^|/)bower_components/",
    "(^|/)bulma\\.(css|sass|scss)$",
    "(^|/)cache/",
    "(^|/)ckeditor\\.js$",
    "(^|/)config\\.guess$",
    "(^|/)config\\.sub$",
    "(^|/)configure$",
    "(^|/)controls\\.js$",
    "(^|/)cordova([^.]*)\\.js$",
    "(^|/)cordova\\-\\d\\.\\d(\\.\\d)?\\.js$",
    "(^|/)cpplint\\.py",
    "(^|/)custom\\.bootstrap([^\\s]*)(js|css|less|scss|styl)$",
    "(^|/)dist/",
    "(^|/)docs?/_?(build|themes?|templates?|static)/",
    "(^|/)dojo\\.js$",
    "(^|/)dotnet-install\\.(ps1|sh)$",
    "(^|/)dragdrop\\.js$",
    "(^|/)effects\\.js$",
    "(^|/)env/",
    "(^|/)erlang\\.mk",
    "(^|/)extjs/.*?\\.html$",
    "(^|/)extjs/.*?\\.js$",
    "(^|/)extjs/.*?\\.properties$",
    "(^|/)extjs/.*?\\.txt$",
    "(^|/)extjs/.*?\\.xml$",
    "(^|/)extjs/\\.sencha/",
    "(^|/)extjs/builds/",
    "(^|/)extjs/cmd/",
    "(^|/)extjs/docs/",
    "(^|/)extjs/examples/",
    "(^|/)extjs/locale/",
    "(^|/)extjs/packages/",
    "(^|/)extjs/plugins/",
    "(^|/)extjs/resources/",
    "(^|/)extjs/src/",
    "(^|/)extjs/welcome/",
    "(^|/)fabfile\\.py$",
    "(^|/)flow-typed/.*\\.js$",
    "(^|/)font-?awesome/.*\\.(css|less|scss|styl)$",
    "(^|/)font-?awesome\\.(css|less|scss|styl)$",
    "(^|/)fontello(.*?)\\.css$",
    "(^|/)foundation(\\..*)?\\.js$",
    "(^|/)foundation\\.(css|less|scss|styl)$",
    "(^|/)fuelux\\.js",
    "(^|/)gradle/wrapper/",
    "(^|/)gradlew$",
    "(^|/)gradlew\\.bat$",
    "(^|/)html5shiv\\.js$",
    "(^|/)inst/extdata/",
    "(^|/)jquery([^.]*)\\.js$",
    "(^|/)jquery([^.]*)\\.unobtrusive\\-ajax\\.js$",
    "(^|/)jquery([^.]*)\\.validate(\\.unobtrusive)?\\.js$",
    "(^|/)jquery\\-\\d\\.\\d+(\\.\\d+)?\\.js$",
    "(^|/)jquery\\-ui(\\-\\d\\.\\d+(\\.\\d+)?)?(\\.\\w+)?\\.(js|css)$",
    "(^|/)jquery\\.(ui|effects)\\.([^.]*)\\.(js|css)$",
    "(^|/)jquery\\.dataTables\\.js",
    "(^|/)jquery\\.fancybox\\.(js|css)",
    "(^|/)jquery\\.fileupload(-\\w+)?\\.js$",
    "(^|/)jquery\\.fn\\.gantt\\.js",
    "(^|/)knockout-(\\d+\\.){3}(debug\\.)?js$",
    "(^|/)leaflet\\.draw-src\\.js",
    "(^|/)leaflet\\.draw\\.css",
    "(^|/)leaflet\\.spin\\.js",
    "(^|/)libtool\\.m4",
    "(^|/)ltoptions\\.m4",
    "(^|/)ltsugar\\.m4",
    "(^|/)ltversion\\.m4",
    "(^|/)lt~obsolete\\.m4",
    "(^|/)materialize\\.(css|less|scss|styl|js)$",
    "(^|/)modernizr\\-\\d\\.\\d+(\\.\\d+)?\\.js$",
    "(^|/)modernizr\\.custom\\.\\d+\\.js$",
    "(^|/)mootools([^.]*)\\d+\\.\\d+.\\d+([^.]*)\\.js$",
    "(^|/)mvnw$",
    "(^|/)mvnw\\.cmd$",
    "(^|/)node_modules/",
    "(^|/)normalize\\.(css|less|scss|styl)$",
    "(^|/)octicons\\.css",
    "(^|/)pdf\\.worker\\.js",
    "(^|/)proguard-rules\\.pro$",
    "(^|/)proguard\\.pro$",
    "(^|/)prototype(.*)\\.js$",
    "(^|/)puphpet/",
    "(^|/)react(-[^.]*)?\\.js$",
    "(^|/)run\\.n$",
    "(^|/)select2/.*\\.(css|scss|js)$",
    "(^|/)shBrush([^.]*)\\.js$",
    "(^|/)shCore\\.js$",
    "(^|/)shLegacy\\.js$",
    "(^|/)skeleton\\.(css|less|scss|styl)$",
    "(^|/)slick\\.\\w+.js$",
    "(^|/)sprockets-octicons\\.scss",
    "(^|/)testdata/",
    "(^|/)tiny_mce([^.]*)\\.js$",
    "(^|/)tiny_mce/(langs|plugins|themes|utils)",
    "(^|/)vendors?/",
    "(^|/)waf$",
    "(^|/)wicket-leaflet\\.js",
    "(^|/)yahoo-([^.]*)\\.js$",
    "(^|/)yui([^.]*)\\.js$",
    "(^|\\/)d3(\\.v\\d+)?([^.]*)\\.js$",
    "-vsdoc\\.js$",
    "\\.imageset/",
    "\\.intellisense\\.js$",
    "\\.xctemplate/",
    "^[Dd]ependencies/",
    "^debian/",
    "^deps/",
    "^rebar$",
];

/// Generated file patterns (from GitHub Linguist generated.rb)
pub const GENERATED_PATTERNS_FROM_LINGUIST: &[&str] = &[
    " ",
    "        # name=",
    "# Microsoft Developer Studio Generated Build File",
    "# This file is automatically generated by Racc",
    "#include <jni.h>",
    "% Generated by roxygen2: do not edit by hand",
    "(function() {",
    ".Rd",
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".css",
    ".dart",
    ".dsp",
    ".eps",
    ".frm",
    ".g",
    ".go",
    ".h",
    ".htm",
    ".html",
    ".java",
    ".js",
    ".lua",
    ".m",
    ".map",
    ".meta",
    ".mod",
    ".nib",
    ".pfa",
    ".php",
    ".proto",
    ".ps",
    ".py",
    ".rb",
    ".rbi",
    ".ts",
    ".xcuserstate",
    ".xcworkspacedata",
    ".xhtml",
    ".xml",
    ".yml",
    ".yy",
    ".yyp",
    "/* DO NOT EDIT THIS FILE - it is machine generated */",
    "/* The following code was generated by JFlex ",
    "/* generated by jison-lex ",
    "/* parser generated by jison ",
    "// Generated by the gRPC",
    "// This is a generated file. Not intended for manual editing.",
    "<!-- This is an automatically generated file.",
    "</doc>",
    "<assembly>",
    "<doc>",
    "Autogenerated by Thrift Compiler",
    "Automatically created by Devel::PPPort",
    "Code generated by protoc-gen-ts_proto. DO NOT EDIT.",
    "DO NOT EDIT MANUALLY",
    "EAGLE",
    "GENERATED CODE -- DO NOT EDIT!",
    "GFORTRAN module version ",
    "Generated by Cython",
    "Generated by Haxe",
    "Generated by the protocol buffer compiler.  DO NOT EDIT!",
    "PCBNEW-LibModule-V",
    "TYPE=VIEW",
    "This file is generated by jOOQ.",
    "This file was autogenerated by go-to-protobuf",
    "[^",
    "\\n",
    "]\\Z/, ",
    "]|[",
    "content",
    "fileFormatVersion: ",
    "generated by Xtest",
    "generator",
    "name",
    "recorded_with: VCR",
    "value",
    "version",
    "}).call(this);",
];

/// Binary file extensions detected by GitHub Linguist
pub const BINARY_PATTERNS_FROM_LINGUIST: &[&str] = &[];
